### ISSUE TITLE
Error when generate_waymo_data

### ISSUE THREAD

**Issue by yanconglin** [Lilac-Lee/FastNSF#2]
https://github.com/Lilac-Lee/FastNSF/blob/a40aac27f196571b247a52520c9ba7b0d08bbd8b/utils/generate_waymo_data.py#L106
```
Traceback (most recent call last):
  File "FastNSF-main/utils/generate_waymo_data.py", line 581, in <module>
    gen_flow_func(args)
  File "FastNSF-main/utils/generate_waymo_data.py", line 289, in gen_flow_func
    _, flows, _, _, _, _ = convert_range_image_to_point_cloud_flow(frame, range_images, range_images_flow, camera_projections, range_image_top_pose)
  File "FastNSF-main/utils/generate_waymo_data.py", line 108, in convert_range_image_to_point_cloud_flow
    range_image_flow = range_images_flow[c.name][ri_index]
KeyError: 1
```

Hi,
Thank you for releasing the code. Unfortunately, I encountered a bug when generating the waymo scene flow dataset. Could you please double check if that works on your side? In my case, I would like to have the full lidar scan without ground removal. 

Btw, would it be possible to release the the argo dataset used in your paper, without removing ground points? 

Thank you.

**Comment by Lilac-Lee** [comment]
Hi @yanconglin, the code was tested correctly on my side. Please check [this instruction](https://github.com/Lilac-Lee/FastNSF/blob/main/utils/WAYMO_OPEN_README.md) for Waymo Open scene flow dataset generation. If you do not want to remove the ground points, you could check the code at [L342-L347](https://github.com/Lilac-Lee/FastNSF/blob/main/utils/generate_waymo_data.py#L342).

If you want to use the Argoverse dataset without removing ground points, you could check [this code](https://github.com/Lilac-Lee/Neural_Scene_Flow_Prior/blob/main/preprocess_sf_argoverse.py#L75).

Cheers.

**Comment by yanconglin** [comment]
issue closed. Instead, I chose a different waymo scene flow dataset. There are several alternative (and more comprehensive) Waymo scene flow subsets available, such as the one from [zero-flow](https://github.com/kylevedder/zeroflow) and the one from [PCA](https://github.com/prs-eth/PCAccumulation).
