### ISSUE TITLE
2D or 3D scene flow estimation?

### ISSUE THREAD

**Issue by TedLentsch** [Lilac-Lee/FastNSF#3]
I checked the [demo](https://github.com/Lilac-Lee/FastNSF/blob/main/demo/optimize_2d_fastNSF_dt.ipynb) notebook and the MLP is used to predict a 2D flow, i.e. the ``Neural_Prior`` class is initialized with ``dim_x=2``. However, the function ``optimize_neural_prior`` in the script [optimization.py](https://github.com/Lilac-Lee/FastNSF/blob/main/optimization.py) creates a class instance without providing the ``dim_x`` argument, i.e. the default of ``dim_x=3`` is used, so 3D flow is predicted. Therefore, which setting should be used according to the authors?

**Comment by Lilac-Lee** [comment]
Hi, @TedLentsch, scene flow describes the 3D motion field, therefore, our project targets 3D point cloud-based scene flow estimation. 
The demo notebook is just a 2D example for better visualization and understanding. 
Cheers.
